** AUTHOR	: MANOJ K
** DATE 	: 18-06-2024
** PRO.NAME	: CURSOR FOR UPDATING WORKING OR NON WORKING DAY FOR ORDERDATE COLUMN
** QUERY	:

				DECLARE @SALESORDERID INT
				DECLARE @ORDERDATE DATE
				DECLARE @WEEKDAYS VARCHAR (255)
				DECLARE @DAY_INFO VARCHAR (225)

				DECLARE DAYSC CURSOR FOR SELECT SALESORDERID, ORDERDATE FROM SALESORDERTAB
				OPEN DAYSC
				 FETCH NEXT FROM DAYSC INTO @SALESORDERID, @ORDERDATE
				 WHILE @@FETCH_STATUS=0
					 BEGIN 
					   SET @WEEKDAYS  = DATENAME(WEEKDAY,@ORDERDATE)
					   UPDATE SALESORDERTAB SET WEEKDAYS = @WEEKDAYS WHERE SALESORDERID= @SALESORDERID
		  
									  SET @DAY_INFO = DATEPART(DW, @ORDERDATE)
											IF @DAY_INFO IN (1,7)
												BEGIN
													UPDATE SALESORDERTAB SET DAY_INFO = 'HOLIDAY' WHERE SALESORDERID = @SALESORDERID
													PRINT 'HOLIDAY.......... YEAH'
												END 
											ELSE 
												BEGIN
													UPDATE SALESORDERTAB SET DAY_INFO = 'WORKINGDAY' WHERE SALESORDERID = @SALESORDERID
													PRINT 'OOPS........'
												END

							
											  FETCH NEXT FROM DAYSC INTO @SALESORDERID, @ORDERDATE
											END	
								
						  CLOSE DAYSC
				 DEALLOCATE DAYSC

				 --EXEC CURSOR_PRO