** AUTHOR	: MANOJ K
** DATE 	: 18-06-2024
** PRO.NAME	: WRITE A STORED PROCEDURE TO FIND THE HIGHEST ORDERED PRODUCT FOR EVERY CUSTOMER, 
					IF HE HAS TWO PRODUCT AT SAME QUANTITY CHOOSE FIRST PRODUCT BASED ON ALPHABETICAL ASCENDING ORDER 

** QUERY	:
					CREATE OR ALTER PROCEDURE CUSTOMER_TOP_PRODUCT @ID INT 
					AS
					WITH A AS (SELECT CUSTOMERID,
									  PRODUCTID,
									  SUM(ORDERQTY) AS ORDERQTY
											FROM SALES.SALESORDERHEADER H 
													INNER JOIN SALES.SALESORDERDETAIL D ON H.SALESORDERID = D.SALESORDERID
														GROUP BY CUSTOMERID, PRODUCTID),

						 B AS (SELECT CUSTOMERID,  
									  NAME,
									  ORDERQTY,
									  ROW_NUMBER () OVER (PARTITION BY CUSTOMERID ORDER BY ORDERQTY DESC, NAME ASC) AS ORDERING
											 FROM A 
												INNER JOIN PRODUCTION.PRODUCT P ON A.PRODUCTID = P.PRODUCTID 
												   )
						
								SELECT CUSTOMERID,
									   NAME,
									   ORDERQTY 
											FROM B 
												WHERE ORDERING = 1 AND CUSTOMERID = 29909
													ORDER BY CUSTOMERID DESC