** AUTHOR	: MANOJ K
** DATE 	: 24-06-2024
** PRO.NAME	: TO FIND THE NAME OF CUSTOMER ID, SALESPERSON ID, TERRITORY ID
**SQL QUERY	:

				SELECT  DISTINCT H.SALESORDERID, H.CUSTOMERID,C.PERSONID,P.BUSINESSENTITYID,P.FIRSTNAME, P.LASTNAME,
									H.TERRITORYID, T.NAME, R.NAME, H.SALESPERSONID, CONCAT(Q.FIRSTNAME,' ',Q.LASTNAME) AS SALESPERSON_NAME

				FROM SALES.SALESORDERHEADER H INNER JOIN SALES.CUSTOMER C ON H.CUSTOMERID = C.CUSTOMERID 
											  LEFT JOIN PERSON.PERSON P ON C.PERSONID = P.BUSINESSENTITYID 
											  INNER JOIN SALES.SALESTERRITORY T ON H.TERRITORYID = T.TERRITORYID 
											  INNER JOIN PERSON.COUNTRYREGION R ON T.COUNTRYREGIONCODE = R.COUNTRYREGIONCODE
											  LEFT JOIN PERSON.PERSON Q ON H.SALESPERSONID =Q.BUSINESSENTITYID
						--WHERE H.SALESORDERID = 57625
							ORDER BY SALESORDERID