** AUTHOR	: MANOJ K
** DATE		: 18-06-2024
** PRO.NAME	: NO OF PARTS IN SALESORDER DETAIL WITH TOTAL QUANTITY AND TOTAL PRICE OF THE QUANTITY. 
** SQL QUERY:
				SELECT H.SALESORDERID, COUNT(D.SALESORDERDETAILID) AS NO_OF_ITEMS , 
										SUM (D.ORDERQTY) AS TOTAL_ORDERED_QUANTITY, 
										CEILING(SUM(D.LINETOTAL)) AS TOTAL_AMOUNT

					FROM SALES.SALESORDERHEADER H 
						INNER JOIN SALES.SALESORDERDETAIL D ON H.SALESORDERID = D. SALESORDERID 
							GROUP BY H.SALESORDERID 
							--HAVING H.SALESORDERID = 43659
								ORDER BY H.SALESORDERID DESC;




** DESCRIPTION:
			    --I JOINED TWO TABLES THROUGH INNER JOIN TO GET MATCHED RECORDS BASED ON SALESOREDERID FROM TWO TABLES. 
				--TO GET THE TOTAL NO OF PARTS AND THIER TOTAL VALUE I USED 'AGGREGATE FUNCTION' ,COUNT AND SUM TO ACHEIVE THIS
				--I GROUPED SALESOREDERID TO ACHEIVE THE AGGREAGTE FUNCTION I USED IN ABOVE QUERY.
				--BY COUNTING THE SALESORDERDETAILID WE GET NO OF PARTS AND BY SUMING THIER QUANTITY WE CAN GET TOAL QUNTITY OF THE SALAESORDER
				--NOW TO GET THE TOTAL VALUE OF SALAESORDER SUMING THE LINE TOTAL  AND TO GET A WHOLE NUMBER I USED CEILING FUCNTION.
				--FOR ARRANGING THE DATA IN TABLE I USED  SALAESORDERID AS A KEY COLUMN .