** AUTHOR	: MANOJ K
** DATE 	: 19-06-2024
** PRO.NAME	: TO FIND THE DETAILS OF PRODUCT USING PRODUCT ID
**SQL QUERY	:

				SELECT D.PRODUCTID,PRODUCTNUMBER,NAME, SUM(ORDERQTY) AS NO_OF_QUANTITY
					FROM SALES.SALESORDERDETAIL D INNER JOIN PRODUCTION.PRODUCT P 
						ON D.PRODUCTID = P.PRODUCTID
							GROUP BY D.PRODUCTID,PRODUCTNUMBER,NAME
								ORDER BY 1;

				--SELECT COUNT(PRODUCTID) FROM SALES.SALESORDERDETAIL;