** AUTHOR	: MANOJ K
** DATE 	: 18-06-2024
** PRO.NAME	: QUERY TO GET SHIPPING DAYS AND DUE DAYS  FOR AN SALAES ORDER WITH TYPES OF PARTS AND THIER TOTAL QUANTITY
** QUERY	:

			WITH TOTAL_QUANTITY AS (SELECT SALESORDERID, SUM(ORDERQTY) AS TOTAL_QUANTITY , 
														COUNT(SALESORDERDETAILID)AS TYPES_OF_PARTS  
										FROM SALES.SALESORDERDETAIL 
											GROUP  BY SALESORDERID )

				 SELECT H.SALESORDERID, G.TYPES_OF_PARTS, G.TOTAL_QUANTITY, ORDERDATE, DUEDATE, SHIPDATE ,
						DATEDIFF(DAY, ORDERDATE,SHIPDATE) AS DAYS_FOR_DISPATCH,
						DATEDIFF(DAY, ORDERDATE,DUEDATE) AS NO_OF_DUE_DAYS, D.CARRIERTRACKINGNUMBER 

					FROM SALES.SALESORDERHEADER H INNER JOIN SALES.SALESORDERDETAIL D 
							ON H.SALESORDERID = D.SALESORDERID INNER JOIN TOTAL_QUANTITY G
									ON D.SALESORDERID = G.SALESORDERID
										ORDER BY ORDERDATE ; 
	
** DESCRIPTION: 
			
				--TO ACHEIVE THE OBJECTIVE I USED DATEDIFF TO FIND THE DIFF B/W TO DATES TO KNOW THE SHIPING DAYS AND DUE DAYS
				--ADDITIONALLY I ADDED TOTAL QUNTITY AND NO OF PARTS FOR A SALAES ORDER AND CARRIER TRACKING NUMBER
				--TO GET THESE DATA I USED SUBQUERY TO GET A TEMPORARY RESULT OF AGGREAGTED OUTPUT.
				--IN SUBQUERY I SUM OF ORDER QUANTITY AND COUNT OF ORDERDETAILID TO TOTAL QUANTITY AND TYPES OF PARTS
				--FOR BETTER READABILITY I USED CTE IN OUR QUERY				
				--NOW I JOINED BOTH ORDERDETAIL , HEADER AND CTE TO GET THE OBJECTIVE RESULTS
				