** AUTHOR	: MANOJ K
** DATE 	: 18-06-2024
** PRO.NAME	: TO FIND THE TOTAL PURCHASED ORDER PLACED BY EACH EMPLOYEE AND ITS VALUE.
** QUERY	:

				WITH H AS (SELECT COUNT(PURCHASEORDERID) AS TOTAL_PURCHASE_ORDER ,
								  EMPLOYEEID,
								  SUM(TOTALDUE) AS TOTAL_DUE

									FROM PURCHASING.PURCHASEORDERHEADER 
										GROUP BY  EMPLOYEEID )


				SELECT EMPLOYEEID,TOTAL_PURCHASE_ORDER,  
					   CONCAT(FIRSTNAME,' ',LASTNAME) AS EMPLOYEE_NAME,
					   CAST(TOTAL_DUE AS DECIMAL(10,2) ) AS PURCHASETOTAL 
						
					   FROM H
								INNER JOIN PERSON.PERSON P ON H.EMPLOYEEID = P.BUSINESSENTITYID 
				